/**
 * app/api/auth/verify-email/route.ts
 *
 * GET /api/auth/verify-email?token=<hex>
 *
 * Marks the user's email as verified. Called when the user clicks
 * the link in their registration email.
 *
 * Security:
 *   - Token is 256-bit random hex (generated by generateSecureToken)
 *   - Expiry is checked against the DB timestamp
 *   - Token is deleted after a single use (one-time-use)
 *   - Already-verified accounts are handled gracefully (idempotent)
 */

import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const token = searchParams.get("token")?.trim();

  // Basic shape check — our tokens are 64-char hex strings
  if (!token || !/^[a-f0-9]{64}$/.test(token)) {
    return NextResponse.json(
      { error: "Invalid or malformed verification link." },
      { status: 400 }
    );
  }

  // Look up by token
  const user = await prisma.user.findUnique({
    where: { verifyToken: token },
    select: {
      id: true,
      isVerified: true,
      verifyTokenExpiry: true,
    },
  });

  if (!user) {
    return NextResponse.json(
      {
        error:
          "This verification link is invalid or has already been used. Please request a new one.",
      },
      { status: 400 }
    );
  }

  // Already verified — idempotent success
  if (user.isVerified) {
    return NextResponse.redirect(new URL("/login?already_verified=true", req.url));
  }

  // Check expiry
  if (!user.verifyTokenExpiry || user.verifyTokenExpiry < new Date()) {
    return NextResponse.json(
      {
        error: "This verification link has expired. Please request a new one.",
        code: "TOKEN_EXPIRED",
      },
      { status: 400 }
    );
  }

  // Mark verified and clear the one-time token
  await prisma.user.update({
    where: { id: user.id },
    data: {
      isVerified: true,
      verifyToken: null,
      verifyTokenExpiry: null,
    },
  });

  // Audit log
  await prisma.auditLog.create({
    data: {
      userId: user.id,
      action: "EMAIL_VERIFIED",
      entity: "User",
      entityId: user.id,
      ipAddress:
        req.headers.get("x-forwarded-for") ??
        req.headers.get("x-real-ip") ??
        null,
    },
  }).catch(() => {});

  return NextResponse.redirect(new URL("/login?verified=true", req.url));
}
